[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  ANTHROPIC_API_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyBULPLaPLq9o73TlMzPuoyuQg1WVyrONrE"
